networks: expense:{}

volumes:
  mysql:

services:
  # docker run -d --name backend --network expense -e DB_HOST=mysql -p 8080:8080 backend:1.0.0
  # this is equivalent to above docker run command
  backend:
    build:
      context: ./backend
    networks:
      - expense
    container_name: backend
    # depends on mysql service to be started first
    depends_on:
      - mysql
    # no need of volume since it is stateless service

  # docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  # this is equivalent to above docker run command
  mysql:
    image: mysql:1.0.0
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  frontend:
    image: frontend:1.0.0
    networks:
      - expense
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    # no need of volume since it is stateless service
